// @ts-nocheck
// This file is autogenerated by scripts/index.ts
// Do not edit this file directly.
import { lazy } from "solid-js"
  
export const Index: Record<string, any> = {
   "tailwindcss": { 
    "accordion-demo": {
      name: "accordion-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/accordion-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/accordion-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "alert-demo": {
      name: "alert-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/alert-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/alert-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "alert-destructive-demo": {
      name: "alert-destructive-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/alert-destructive-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/alert-destructive-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "alert-dialog-demo": {
      name: "alert-dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/alert-dialog-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/alert-dialog-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "badge-demo": {
      name: "badge-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/badge-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/badge-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "badge-destructive-demo": {
      name: "badge-destructive-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/badge-destructive-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/badge-destructive-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "badge-outline-demo": {
      name: "badge-outline-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/badge-outline-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/badge-outline-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "badge-secondary-demo": {
      name: "badge-secondary-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/badge-secondary-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/badge-secondary-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/button-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/button-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "button-destructive-demo": {
      name: "button-destructive-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/button-destructive-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/button-destructive-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "button-ghost-demo": {
      name: "button-ghost-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/button-ghost-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/button-ghost-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "button-left-icon-demo": {
      name: "button-left-icon-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/button-left-icon-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/button-left-icon-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "button-link-demo": {
      name: "button-link-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/button-link-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/button-link-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "button-loading-demo": {
      name: "button-loading-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/button-loading-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/button-loading-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "button-outline-demo": {
      name: "button-outline-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/button-outline-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/button-outline-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "button-secondary-demo": {
      name: "button-secondary-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/button-secondary-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/button-secondary-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "calendar-demo": {
      name: "calendar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/calendar-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/calendar-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "calendar-range-demo": {
      name: "calendar-range-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/calendar-range-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/calendar-range-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "card-demo": {
      name: "card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/card-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/card-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "carouse-plugin-demo": {
      name: "carouse-plugin-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/carouse-plugin-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/carouse-plugin-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "carousel-demo": {
      name: "carousel-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/carousel-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/carousel-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "carousel-orientation-demo": {
      name: "carousel-orientation-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/carousel-orientation-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/carousel-orientation-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "carousel-size-demo": {
      name: "carousel-size-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/carousel-size-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/carousel-size-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "checkbox-demo": {
      name: "checkbox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/checkbox-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/checkbox-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "checkbox-disabled-demo": {
      name: "checkbox-disabled-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/checkbox-disabled-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/checkbox-disabled-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "collapsible-demo": {
      name: "collapsible-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/collapsible-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/collapsible-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "combobox-demo": {
      name: "combobox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/combobox-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/combobox-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "combobox-disabled-demo": {
      name: "combobox-disabled-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/combobox-disabled-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/combobox-disabled-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "combobox-error-demo": {
      name: "combobox-error-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/combobox-error-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/combobox-error-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "combobox-group-demo": {
      name: "combobox-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/combobox-group-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/combobox-group-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "combobox-multi-demo": {
      name: "combobox-multi-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/combobox-multi-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/combobox-multi-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "command-demo": {
      name: "command-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/command-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/command-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "command-dialog-demo": {
      name: "command-dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/command-dialog-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/command-dialog-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "context-menu-demo": {
      name: "context-menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/context-menu-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/context-menu-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "dialog-demo": {
      name: "dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/dialog-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/dialog-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "drawer-demo": {
      name: "drawer-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/drawer-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/drawer-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "drawer-side-demo": {
      name: "drawer-side-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/drawer-side-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/drawer-side-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "dropdown-menu-demo": {
      name: "dropdown-menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/dropdown-menu-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/dropdown-menu-demo")),
      source: "",
      category: "",
      subcategory: ""
    }, 
    "hover-card-demo": {
      name: "hover-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "../../packages/tailwindcss/src/examples/hover-card-demo.tsx",
        type: "registry:example",
        target: "",
        content: ""
      }],
      component: lazy(() => import("@repo/tailwindcss/examples/hover-card-demo")),
      source: "",
      category: "",
      subcategory: ""
    },
  },
  }
  