// @ts-nocheck
// This file is autogenerated by scripts/build-contents.ts
// Do not edit this file directly.
import type { Component } from "solid-js";
import { lazy } from "solid-js";

export const Contents: Record<string, Record<"component", Component<unknown>>> = {
  "/docs/about": {
    component: lazy(() => import("@/contents/docs/about.mdx"))
  },
  "/docs/changelog": {
    component: lazy(() => import("@/contents/docs/changelog.mdx"))
  },
  "/docs/cli": {
    component: lazy(() => import("@/contents/docs/cli.mdx"))
  },
  "/docs/components/accordion": {
    component: lazy(() => import("@/contents/docs/components/accordion.mdx"))
  },
  "/docs/components/alert-dialog": {
    component: lazy(() => import("@/contents/docs/components/alert-dialog.mdx"))
  },
  "/docs/components/alert": {
    component: lazy(() => import("@/contents/docs/components/alert.mdx"))
  },
  "/docs/components/badge": {
    component: lazy(() => import("@/contents/docs/components/badge.mdx"))
  },
  "/docs/components/button": {
    component: lazy(() => import("@/contents/docs/components/button.mdx"))
  },
  "/docs/components/card": {
    component: lazy(() => import("@/contents/docs/components/card.mdx"))
  },
  "/docs/components/carousel": {
    component: lazy(() => import("@/contents/docs/components/carousel.mdx"))
  },
  "/docs/components/checkbox": {
    component: lazy(() => import("@/contents/docs/components/checkbox.mdx"))
  },
  "/docs/components/collapsible": {
    component: lazy(() => import("@/contents/docs/components/collapsible.mdx"))
  },
  "/docs/components/combobox": {
    component: lazy(() => import("@/contents/docs/components/combobox.mdx"))
  },
  "/docs/components/command": {
    component: lazy(() => import("@/contents/docs/components/command.mdx"))
  },
  "/docs/components/context-menu": {
    component: lazy(() => import("@/contents/docs/components/context-menu.mdx"))
  },
  "/docs/components/data-table": {
    component: lazy(() => import("@/contents/docs/components/data-table.mdx"))
  },
  "/docs/components/date-picker": {
    component: lazy(() => import("@/contents/docs/components/date-picker.mdx"))
  },
  "/docs/components/dialog": {
    component: lazy(() => import("@/contents/docs/components/dialog.mdx"))
  },
  "/docs/components/drawer": {
    component: lazy(() => import("@/contents/docs/components/drawer.mdx"))
  },
  "/docs/components/dropdown-menu": {
    component: lazy(() => import("@/contents/docs/components/dropdown-menu.mdx"))
  },
  "/docs/components/hover-card": {
    component: lazy(() => import("@/contents/docs/components/hover-card.mdx"))
  },
  "/docs/components/image": {
    component: lazy(() => import("@/contents/docs/components/image.mdx"))
  },
  "/docs/components/menubar": {
    component: lazy(() => import("@/contents/docs/components/menubar.mdx"))
  },
  "/docs/components/number-field": {
    component: lazy(() => import("@/contents/docs/components/number-field.mdx"))
  },
  "/docs/components/otp-field": {
    component: lazy(() => import("@/contents/docs/components/otp-field.mdx"))
  },
  "/docs/components/pagination": {
    component: lazy(() => import("@/contents/docs/components/pagination.mdx"))
  },
  "/docs/components/popover": {
    component: lazy(() => import("@/contents/docs/components/popover.mdx"))
  },
  "/docs/components/progress": {
    component: lazy(() => import("@/contents/docs/components/progress.mdx"))
  },
  "/docs/components/radio-group": {
    component: lazy(() => import("@/contents/docs/components/radio-group.mdx"))
  },
  "/docs/components/resizable": {
    component: lazy(() => import("@/contents/docs/components/resizable.mdx"))
  },
  "/docs/components/select": {
    component: lazy(() => import("@/contents/docs/components/select.mdx"))
  },
  "/docs/components/separator": {
    component: lazy(() => import("@/contents/docs/components/separator.mdx"))
  },
  "/docs/components/sheet": {
    component: lazy(() => import("@/contents/docs/components/sheet.mdx"))
  },
  "/docs/components/skeleton": {
    component: lazy(() => import("@/contents/docs/components/skeleton.mdx"))
  },
  "/docs/components/sonner": {
    component: lazy(() => import("@/contents/docs/components/sonner.mdx"))
  },
  "/docs/components/switch": {
    component: lazy(() => import("@/contents/docs/components/switch.mdx"))
  },
  "/docs/components/table": {
    component: lazy(() => import("@/contents/docs/components/table.mdx"))
  },
  "/docs/components/tabs": {
    component: lazy(() => import("@/contents/docs/components/tabs.mdx"))
  },
  "/docs/components/textarea": {
    component: lazy(() => import("@/contents/docs/components/textarea.mdx"))
  },
  "/docs/components/textfield": {
    component: lazy(() => import("@/contents/docs/components/textfield.mdx"))
  },
  "/docs/components/toast": {
    component: lazy(() => import("@/contents/docs/components/toast.mdx"))
  },
  "/docs/components/toggle-group": {
    component: lazy(() => import("@/contents/docs/components/toggle-group.mdx"))
  },
  "/docs/components/toggle": {
    component: lazy(() => import("@/contents/docs/components/toggle.mdx"))
  },
  "/docs/components/tooltip": {
    component: lazy(() => import("@/contents/docs/components/tooltip.mdx"))
  },
  "/docs/components-json": {
    component: lazy(() => import("@/contents/docs/components-json.mdx"))
  },
  "/docs/dark-mode": {
    component: lazy(() => import("@/contents/docs/dark-mode.mdx"))
  },
  "/docs/figma": {
    component: lazy(() => import("@/contents/docs/figma.mdx"))
  },
  "/docs": {
    component: lazy(() => import("@/contents/docs/index.mdx"))
  },
  "/docs/installation/astro": {
    component: lazy(() => import("@/contents/docs/installation/astro.mdx"))
  },
  "/docs/installation": {
    component: lazy(() => import("@/contents/docs/installation/index.mdx"))
  },
  "/docs/installation/manual": {
    component: lazy(() => import("@/contents/docs/installation/manual.mdx"))
  },
  "/docs/installation/solid-start": {
    component: lazy(() => import("@/contents/docs/installation/solid-start.mdx"))
  },
  "/docs/theming": {
    component: lazy(() => import("@/contents/docs/theming.mdx"))
  },
  "/docs/typography": {
    component: lazy(() => import("@/contents/docs/typography.mdx"))
  }
};
