/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ViewNameRouteImport } from './routes/view.$name'
import { Route as MainDocsRouteImport } from './routes/_main/docs'
import { Route as MainDocsSplatRouteImport } from './routes/_main/docs.$'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const ViewNameRoute = ViewNameRouteImport.update({
  id: '/view/$name',
  path: '/view/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const MainDocsRoute = MainDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => MainRoute,
} as any)
const MainDocsSplatRoute = MainDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MainDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/test': typeof TestRoute
  '/docs': typeof MainDocsRouteWithChildren
  '/view/$name': typeof ViewNameRoute
  '/': typeof MainIndexRoute
  '/docs/$': typeof MainDocsSplatRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/docs': typeof MainDocsRouteWithChildren
  '/view/$name': typeof ViewNameRoute
  '/': typeof MainIndexRoute
  '/docs/$': typeof MainDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/test': typeof TestRoute
  '/_main/docs': typeof MainDocsRouteWithChildren
  '/view/$name': typeof ViewNameRoute
  '/_main/': typeof MainIndexRoute
  '/_main/docs/$': typeof MainDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/test' | '/docs' | '/view/$name' | '/' | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/test' | '/docs' | '/view/$name' | '/' | '/docs/$'
  id:
    | '__root__'
    | '/_main'
    | '/test'
    | '/_main/docs'
    | '/view/$name'
    | '/_main/'
    | '/_main/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  TestRoute: typeof TestRoute
  ViewNameRoute: typeof ViewNameRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/view/$name': {
      id: '/view/$name'
      path: '/view/$name'
      fullPath: '/view/$name'
      preLoaderRoute: typeof ViewNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/docs': {
      id: '/_main/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof MainDocsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/docs/$': {
      id: '/_main/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof MainDocsSplatRouteImport
      parentRoute: typeof MainDocsRoute
    }
  }
}

interface MainDocsRouteChildren {
  MainDocsSplatRoute: typeof MainDocsSplatRoute
}

const MainDocsRouteChildren: MainDocsRouteChildren = {
  MainDocsSplatRoute: MainDocsSplatRoute,
}

const MainDocsRouteWithChildren = MainDocsRoute._addFileChildren(
  MainDocsRouteChildren,
)

interface MainRouteChildren {
  MainDocsRoute: typeof MainDocsRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDocsRoute: MainDocsRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  TestRoute: TestRoute,
  ViewNameRoute: ViewNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
