// @ts-nocheck
// This file is autogenerated
// Do not edit this file directly.
import type { JSX } from "solid-js";
import { lazy } from "solid-js";

interface Content {
  component: JSX.Element
  data: {
    title: string
    description: string
    component?: boolean
    link?: {
      doc?: string
      api?: string
    }
    toc?: boolean 
  } 
  headings: {
    depth: number
    slug: string
    text: string
  }[]
}

export const Contents : Record<string, Content> = {
  "components/button": {
    component: lazy(() => import("@/content/docs/components/button.mdx")),
    data: {
  "title": "Button",
  "description": "Displays a button or a component that looks like a button.",
  "component": true,
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/button",
    "api": "https://kobalte.dev/docs/core/components/button#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Destructive",
    "slug": "destructive"
  },
  {
    "depth": 3,
    "text": "Ghost",
    "slug": "ghost"
  },
  {
    "depth": 3,
    "text": "With Icon",
    "slug": "with-icon"
  },
  {
    "depth": 3,
    "text": "Loading",
    "slug": "loading"
  },
  {
    "depth": 3,
    "text": "Outline",
    "slug": "outline"
  },
  {
    "depth": 3,
    "text": "Secondary",
    "slug": "secondary"
  }
]
  },
  "introduction": {
    component: lazy(() => import("@/content/docs/introduction.mdx")),
    data: {
  "title": "Introduction",
  "description": "Re-usable components built using Kobalte UI and your choice of CSS frameworks."
},
    headings: [
  {
    "depth": 2,
    "text": "Open Code",
    "slug": "open-code"
  },
  {
    "depth": 2,
    "text": "Composition",
    "slug": "composition"
  },
  {
    "depth": 2,
    "text": "Distribution",
    "slug": "distribution"
  },
  {
    "depth": 2,
    "text": "Beautiful Defaults",
    "slug": "beautiful-defaults"
  }
]
  },
};