// @ts-nocheck
// This file is autogenerated
// Do not edit this file directly.
import type { JSX } from "solid-js";
import { lazy } from "solid-js";

interface Content {
  component: JSX.Element
  data: {
    title: string
    description: string
    component?: boolean
    link?: {
      doc?: string
      api?: string
    }
    toc?: boolean 
  } 
  headings: {
    depth: number
    slug: string
    text: string
  }[]
}

export const Contents : Record<string, Content> = {
  "components/accordion": {
    component: lazy(() => import("@/content/docs/components/accordion.mdx")),
    data: {
  "title": "Accordion",
  "description": "A vertically stacked set of interactive headings that each reveal a section of content.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/accordion",
    "api": "https://kobalte.dev/docs/core/components/accordion#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/alert-dialog": {
    component: lazy(() => import("@/content/docs/components/alert-dialog.mdx")),
    data: {
  "title": "Alert Dialog",
  "description": "A modal dialog that interrupts the user with important content and expects a response.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/alert-dialog",
    "api": "https://kobalte.dev/docs/core/components/alert-dialog#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/alert": {
    component: lazy(() => import("@/content/docs/components/alert.mdx")),
    data: {
  "title": "Alert",
  "description": "Displays a callout for user attention.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/alert",
    "api": "https://kobalte.dev/docs/core/components/alert#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Destructive",
    "slug": "destructive"
  }
]
  },
  "components/badge": {
    component: lazy(() => import("@/content/docs/components/badge.mdx")),
    data: {
  "title": "Badge",
  "description": "Displays a badge or a component that looks like a badge.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/badge",
    "api": "https://kobalte.dev/docs/core/components/badge#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Secondary",
    "slug": "secondary"
  },
  {
    "depth": 3,
    "text": "Destructive",
    "slug": "destructive"
  },
  {
    "depth": 3,
    "text": "Outline",
    "slug": "outline"
  }
]
  },
  "components/breadcrumbs": {
    component: lazy(() => import("@/content/docs/components/breadcrumbs.mdx")),
    data: {
  "title": "Breadcrumbs",
  "description": "Displays the path to the current resource using a hierarchy of links.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/breadcrumbs",
    "api": "https://kobalte.dev/docs/core/components/breadcrumbs#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Custom separator",
    "slug": "custom-separator"
  },
  {
    "depth": 3,
    "text": "Dropdown",
    "slug": "dropdown"
  },
  {
    "depth": 3,
    "text": "Collapsed",
    "slug": "collapsed"
  }
]
  },
  "components/button": {
    component: lazy(() => import("@/content/docs/components/button.mdx")),
    data: {
  "title": "Button",
  "description": "Displays a button or a component that looks like a button.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/button",
    "api": "https://kobalte.dev/docs/core/components/button#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Destructive",
    "slug": "destructive"
  },
  {
    "depth": 3,
    "text": "Ghost",
    "slug": "ghost"
  },
  {
    "depth": 3,
    "text": "With Icon",
    "slug": "with-icon"
  },
  {
    "depth": 3,
    "text": "Loading",
    "slug": "loading"
  },
  {
    "depth": 3,
    "text": "Outline",
    "slug": "outline"
  },
  {
    "depth": 3,
    "text": "Secondary",
    "slug": "secondary"
  }
]
  },
  "components/calendar": {
    component: lazy(() => import("@/content/docs/components/calendar.mdx")),
    data: {
  "title": "Calendar",
  "description": "A date field component that allows users to enter and edit date.",
  "link": {
    "doc": "https://corvu.dev/docs/primitives/calendar/",
    "api": "https://corvu.dev/docs/primitives/calendar/#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Range Calendar",
    "slug": "range-calendar"
  }
]
  },
  "components/card": {
    component: lazy(() => import("@/content/docs/components/card.mdx")),
    data: {
  "title": "Card",
  "description": "Displays a card with header, content, and footer."
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/carousel": {
    component: lazy(() => import("@/content/docs/components/carousel.mdx")),
    data: {
  "title": "Carousel",
  "description": "A carousel with motion and swipe built using Embla.",
  "link": {
    "doc": "https://www.embla-carousel.com/get-started/solid",
    "api": "https://www.embla-carousel.com/api"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Sizes",
    "slug": "sizes"
  },
  {
    "depth": 3,
    "text": "Spacing",
    "slug": "spacing"
  },
  {
    "depth": 3,
    "text": "Orientation",
    "slug": "orientation"
  },
  {
    "depth": 2,
    "text": "Options",
    "slug": "options"
  },
  {
    "depth": 2,
    "text": "Plugins",
    "slug": "plugins"
  }
]
  },
  "components/chart": {
    component: lazy(() => import("@/content/docs/components/chart.mdx")),
    data: {
  "title": "Chart",
  "description": "Beautiful charts. Built using Unovis. Copy and paste into your apps."
},
    headings: [
  {
    "depth": 2,
    "text": "Component",
    "slug": "component"
  },
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Chart Config",
    "slug": "chart-config"
  },
  {
    "depth": 2,
    "text": "Theming",
    "slug": "theming"
  },
  {
    "depth": 3,
    "text": "CSS Variables",
    "slug": "css-variables"
  },
  {
    "depth": 3,
    "text": "hex, hsl or oklch",
    "slug": "hex-hsl-or-oklch"
  },
  {
    "depth": 3,
    "text": "Using Colors",
    "slug": "using-colors"
  },
  {
    "depth": 4,
    "text": "Components",
    "slug": "components"
  },
  {
    "depth": 4,
    "text": "Chart Data",
    "slug": "chart-data"
  },
  {
    "depth": 2,
    "text": "Tooltip",
    "slug": "tooltip"
  },
  {
    "depth": 3,
    "text": "Props",
    "slug": "props"
  },
  {
    "depth": 3,
    "text": "Colors",
    "slug": "colors"
  },
  {
    "depth": 3,
    "text": "Custom",
    "slug": "custom"
  }
]
  },
  "components/checkbox": {
    component: lazy(() => import("@/content/docs/components/checkbox.mdx")),
    data: {
  "title": "Checkbox",
  "description": "A control that allows the user to toggle between checked and not checked.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/checkbox",
    "api": "https://kobalte.dev/docs/core/components/checkbox#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Disabled",
    "slug": "disabled"
  }
]
  },
  "components/collapsible": {
    component: lazy(() => import("@/content/docs/components/collapsible.mdx")),
    data: {
  "title": "Collapsible",
  "description": "An interactive component which expands/collapses a panel.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/collapsible",
    "api": "https://kobalte.dev/docs/core/components/collapsible#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/combobox": {
    component: lazy(() => import("@/content/docs/components/combobox.mdx")),
    data: {
  "title": "Combobox",
  "description": "Combines a text input with a listbox, allowing users to filter a list of options to items matching a query.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/combobox",
    "api": "https://kobalte.dev/docs/core/components/combobox#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Disabled",
    "slug": "disabled"
  },
  {
    "depth": 3,
    "text": "Error",
    "slug": "error"
  },
  {
    "depth": 3,
    "text": "Group",
    "slug": "group"
  },
  {
    "depth": 3,
    "text": "Multi",
    "slug": "multi"
  }
]
  },
  "components/command": {
    component: lazy(() => import("@/content/docs/components/command.mdx")),
    data: {
  "title": "Command",
  "description": "Composable command menu.",
  "link": {
    "doc": "https://cmdk-solid.vercel.app"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Dialog",
    "slug": "dialog"
  }
]
  },
  "components/context-menu": {
    component: lazy(() => import("@/content/docs/components/context-menu.mdx")),
    data: {
  "title": "Context Menu",
  "description": "Displays a menu to the user — such as a set of actions or functions — triggered by a button.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/context-menu",
    "api": "https://kobalte.dev/docs/core/components/context-menu#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/data-table": {
    component: lazy(() => import("@/content/docs/components/data-table.mdx")),
    data: {
  "title": "Data Table",
  "description": "Powerful table and datagrids built using TanStack Table.",
  "link": {
    "doc": "https://tanstack.com/table/latest/docs/introduction"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Introduction",
    "slug": "introduction"
  },
  {
    "depth": 2,
    "text": "Table of Contents",
    "slug": "table-of-contents"
  },
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Prerequisites",
    "slug": "prerequisites"
  },
  {
    "depth": 2,
    "text": "Project Structure",
    "slug": "project-structure"
  },
  {
    "depth": 2,
    "text": "Basic Table",
    "slug": "basic-table"
  },
  {
    "depth": 3,
    "text": "Column Definitions",
    "slug": "column-definitions"
  },
  {
    "depth": 3,
    "text": "<DataTable /> component",
    "slug": "datatable--component"
  },
  {
    "depth": 3,
    "text": "Render the table",
    "slug": "render-the-table"
  },
  {
    "depth": 2,
    "text": "Row Actions",
    "slug": "row-actions"
  },
  {
    "depth": 2,
    "text": "Pagination",
    "slug": "pagination"
  },
  {
    "depth": 3,
    "text": "Update <DataTable />",
    "slug": "update-datatable-"
  },
  {
    "depth": 3,
    "text": "Add pagination controls",
    "slug": "add-pagination-controls"
  },
  {
    "depth": 2,
    "text": "Sorting",
    "slug": "sorting"
  },
  {
    "depth": 3,
    "text": "Update <DataTable />",
    "slug": "update-datatable--1"
  },
  {
    "depth": 3,
    "text": "Make header cell sortable",
    "slug": "make-header-cell-sortable"
  },
  {
    "depth": 2,
    "text": "Filtering",
    "slug": "filtering"
  },
  {
    "depth": 3,
    "text": "Update <DataTable />",
    "slug": "update-datatable--2"
  },
  {
    "depth": 2,
    "text": "Visibility",
    "slug": "visibility"
  },
  {
    "depth": 3,
    "text": "Update <DataTable />",
    "slug": "update-datatable--3"
  },
  {
    "depth": 2,
    "text": "Row Selection",
    "slug": "row-selection"
  },
  {
    "depth": 3,
    "text": "Update column definitions",
    "slug": "update-column-definitions"
  },
  {
    "depth": 3,
    "text": "Update <DataTable />",
    "slug": "update-datatable--4"
  },
  {
    "depth": 3,
    "text": "Show selected rows",
    "slug": "show-selected-rows"
  }
]
  },
  "components/date-picker": {
    component: lazy(() => import("@/content/docs/components/date-picker.mdx")),
    data: {
  "title": "Date Picker",
  "description": "A date picker component with range and presets."
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "With range",
    "slug": "with-range"
  }
]
  },
  "components/dialog": {
    component: lazy(() => import("@/content/docs/components/dialog.mdx")),
    data: {
  "title": "Dialog",
  "description": "A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/dialog",
    "api": "https://kobalte.dev/docs/core/components/dialog#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/drawer": {
    component: lazy(() => import("@/content/docs/components/drawer.mdx")),
    data: {
  "title": "Drawer",
  "description": "A draggable dialog that is attached to any side of the viewport.",
  "link": {
    "doc": "https://corvu.dev/docs/primitives/drawer",
    "api": "https://corvu.dev/docs/primitives/drawer/#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Side",
    "slug": "side"
  }
]
  },
  "components/dropdown-menu": {
    component: lazy(() => import("@/content/docs/components/dropdown-menu.mdx")),
    data: {
  "title": "Dropdown Menu",
  "description": "Displays a menu to the user — such as a set of actions or functions — triggered by a button.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/dropdown-menu",
    "api": "https://kobalte.dev/docs/core/components/dropdown-menu#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/file-field": {
    component: lazy(() => import("@/content/docs/components/file-field.mdx")),
    data: {
  "title": "File Field",
  "description": "A file input to upload multiple files, with ability to drag and drop files.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/file-field",
    "api": "https://kobalte.dev/docs/core/components/file-field#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/hover-card": {
    component: lazy(() => import("@/content/docs/components/hover-card.mdx")),
    data: {
  "title": "Hover Card",
  "description": "For sighted users to preview content available behind a link.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/hover-card",
    "api": "https://kobalte.dev/docs/core/components/hover-card#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/menubar": {
    component: lazy(() => import("@/content/docs/components/menubar.mdx")),
    data: {
  "title": "Menubar",
  "description": "A visually persistent menu common in desktop applications that provides quick access to a consistent set of commands.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/menubar",
    "api": "https://kobalte.dev/docs/core/components/menubar#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/navigation-menu": {
    component: lazy(() => import("@/content/docs/components/navigation-menu.mdx")),
    data: {
  "title": "Navigation Menu",
  "description": "A collection of links for navigating websites.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/navigation-menu",
    "api": "https://kobalte.dev/docs/core/components/navigation-menu#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Orientation",
    "slug": "orientation"
  }
]
  },
  "components/number-field": {
    component: lazy(() => import("@/content/docs/components/number-field.mdx")),
    data: {
  "title": "Number Field",
  "description": "A number input that allow users to input custom number entries with a keyboard.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/number-field",
    "api": "https://kobalte.dev/docs/core/components/number-field#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "With Error",
    "slug": "with-error"
  }
]
  },
  "components/otp-field": {
    component: lazy(() => import("@/content/docs/components/otp-field.mdx")),
    data: {
  "title": "OTP Field",
  "description": "An accessible and customizable OTP Input component.",
  "link": {
    "doc": "https://corvu.dev/docs/primitives/otp-field/",
    "api": "https://corvu.dev/docs/primitives/otp-field/#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/pagination": {
    component: lazy(() => import("@/content/docs/components/pagination.mdx")),
    data: {
  "title": "Pagination",
  "description": "Pagination with page navigation, next and previous links.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/pagination",
    "api": "https://kobalte.dev/docs/core/components/pagination#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  }
]
  },
  "components/popover": {
    component: lazy(() => import("@/content/docs/components/popover.mdx")),
    data: {
  "title": "Popover",
  "description": "Displays rich content in a portal, triggered by a button.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/popover",
    "api": "https://kobalte.dev/docs/core/components/popover#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/progress": {
    component: lazy(() => import("@/content/docs/components/progress.mdx")),
    data: {
  "title": "Progress",
  "description": "Displays an indicator showing the completion progress of a task, typically displayed as a progress bar.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/progress",
    "api": "https://kobalte.dev/docs/core/components/progress#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/radio-group": {
    component: lazy(() => import("@/content/docs/components/radio-group.mdx")),
    data: {
  "title": "Radio Group",
  "description": "A set of checkable buttons—known as radio buttons—where no more than one of the buttons can be checked at a time.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/radio-group",
    "api": "https://kobalte.dev/docs/core/components/radio-group#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/resizable": {
    component: lazy(() => import("@/content/docs/components/resizable.mdx")),
    data: {
  "title": "Resizable",
  "description": "A component that divides your interface into resizable sections.",
  "link": {
    "doc": "https://corvu.dev/docs/primitives/resizable",
    "api": "https://corvu.dev/docs/primitives/resizable#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Orientation",
    "slug": "orientation"
  },
  {
    "depth": 3,
    "text": "With Handle",
    "slug": "with-handle"
  }
]
  },
  "components/search": {
    component: lazy(() => import("@/content/docs/components/search.mdx")),
    data: {
  "title": "Search",
  "description": "Search a searchbox text input with a menu. Handle the case where dataset filtering needs to occur outside the combobox component.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/search",
    "api": "https://kobalte.dev/docs/core/components/search#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Inline",
    "slug": "inline"
  }
]
  },
  "components/segmented-control": {
    component: lazy(() => import("@/content/docs/components/segmented-control.mdx")),
    data: {
  "title": "Segmented Control",
  "description": "A linear set of two or more segments, each of which functions as a radio input, and a default value is required.",
  "link": {
    "docs": "https://kobalte.dev/docs/core/components/segmented-control",
    "api": "https://kobalte.dev/docs/core/components/segmented-control#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Orientation",
    "slug": "orientation"
  }
]
  },
  "components/select": {
    component: lazy(() => import("@/content/docs/components/select.mdx")),
    data: {
  "title": "Select",
  "description": "Displays a list of options for the user to pick from—triggered by a button.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/select",
    "api": "https://kobalte.dev/docs/core/components/select#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Error",
    "slug": "error"
  }
]
  },
  "components/separator": {
    component: lazy(() => import("@/content/docs/components/separator.mdx")),
    data: {
  "title": "Separator",
  "description": "Visually or semantically separates content.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/separator",
    "api": "https://kobalte.dev/docs/core/components/separator#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/sidebar": {
    component: lazy(() => import("@/content/docs/components/sidebar.mdx")),
    data: {
  "title": "Sidebar",
  "description": "A composable, themeable and customizable sidebar component."
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Structure",
    "slug": "structure"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Your First Sidebar",
    "slug": "your-first-sidebar"
  },
  {
    "depth": 2,
    "text": "Components",
    "slug": "components"
  },
  {
    "depth": 2,
    "text": "SidebarProvider",
    "slug": "sidebarprovider"
  },
  {
    "depth": 3,
    "text": "Props",
    "slug": "props"
  },
  {
    "depth": 3,
    "text": "Width",
    "slug": "width"
  },
  {
    "depth": 3,
    "text": "Keyboard Shortcut",
    "slug": "keyboard-shortcut"
  },
  {
    "depth": 2,
    "text": "Sidebar",
    "slug": "sidebar"
  },
  {
    "depth": 3,
    "text": "Props",
    "slug": "props-1"
  },
  {
    "depth": 3,
    "text": "side",
    "slug": "side"
  },
  {
    "depth": 3,
    "text": "variant",
    "slug": "variant"
  },
  {
    "depth": 3,
    "text": "collapsible",
    "slug": "collapsible"
  },
  {
    "depth": 2,
    "text": "useSidebar",
    "slug": "usesidebar"
  },
  {
    "depth": 2,
    "text": "Theming",
    "slug": "theming"
  },
  {
    "depth": 2,
    "text": "Styling",
    "slug": "styling"
  }
]
  },
  "components/skeleton": {
    component: lazy(() => import("@/content/docs/components/skeleton.mdx")),
    data: {
  "title": "Skeleton",
  "description": "Visually indicates content loading.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/skeleton",
    "api": "https://kobalte.dev/docs/core/components/skeleton#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/slider": {
    component: lazy(() => import("@/content/docs/components/slider.mdx")),
    data: {
  "title": "Slider",
  "description": "An input where the user selects a value from within a given range.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/slider",
    "api": "https://kobalte.dev/docs/core/components/slider#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Vertical",
    "slug": "vertical"
  },
  {
    "depth": 3,
    "text": "Custom Label",
    "slug": "custom-label"
  }
]
  },
  "components/sonner": {
    component: lazy(() => import("@/content/docs/components/sonner.mdx")),
    data: {
  "title": "Sonner",
  "description": "An opinionated toast component for Solid.",
  "link": {
    "doc": "https://oc1s.github.io/somo",
    "api": "https://oc1s.github.io/somo/toaster/#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/switch": {
    component: lazy(() => import("@/content/docs/components/switch.mdx")),
    data: {
  "title": "Switch",
  "description": "A control that allows the user to toggle between checked and not checked.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/switch",
    "api": "https://kobalte.dev/docs/core/components/switch#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/table": {
    component: lazy(() => import("@/content/docs/components/table.mdx")),
    data: {
  "title": "Table",
  "description": "A responsive table component."
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/tabs": {
    component: lazy(() => import("@/content/docs/components/tabs.mdx")),
    data: {
  "title": "Tabs",
  "description": "A set of layered sections of content—known as tab panels—that are displayed one at a time.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/tabs",
    "api": "https://kobalte.dev/docs/core/components/tabs#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  }
]
  },
  "components/text-field": {
    component: lazy(() => import("@/content/docs/components/text-field.mdx")),
    data: {
  "title": "Text Field",
  "description": "A text input that allow users to input custom text entries with a keyboard.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/text-field",
    "api": "https://kobalte.dev/docs/core/components/text-field#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Disabled",
    "slug": "disabled"
  },
  {
    "depth": 3,
    "text": "Error",
    "slug": "error"
  },
  {
    "depth": 3,
    "text": "File",
    "slug": "file"
  },
  {
    "depth": 3,
    "text": "Text Area",
    "slug": "text-area"
  }
]
  },
  "components/toggle-button": {
    component: lazy(() => import("@/content/docs/components/toggle-button.mdx")),
    data: {
  "title": "Toggle Button",
  "description": "A two-state button that can be either on or off.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/toggle-button",
    "api": "https://kobalte.dev/docs/core/components/toggle-button#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  },
  {
    "depth": 2,
    "text": "Examples",
    "slug": "examples"
  },
  {
    "depth": 3,
    "text": "Outline",
    "slug": "outline"
  },
  {
    "depth": 3,
    "text": "Size",
    "slug": "size"
  },
  {
    "depth": 3,
    "text": "Disabled",
    "slug": "disabled"
  }
]
  },
  "components/toggle-group": {
    component: lazy(() => import("@/content/docs/components/toggle-group.mdx")),
    data: {
  "title": "Toggle Group",
  "description": "A set of two-state buttons that can be toggled on (pressed) or off (not pressed).",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/toggle-group",
    "api": "https://kobalte.dev/docs/core/components/toggle-group#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 2,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "components/tooltip": {
    component: lazy(() => import("@/content/docs/components/tooltip.mdx")),
    data: {
  "title": "Tooltip",
  "description": "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.",
  "link": {
    "doc": "https://kobalte.dev/docs/core/components/tooltip",
    "api": "https://kobalte.dev/docs/core/components/tooltip#api-reference"
  }
},
    headings: [
  {
    "depth": 2,
    "text": "Installation",
    "slug": "installation"
  },
  {
    "depth": 3,
    "text": "Usage",
    "slug": "usage"
  }
]
  },
  "dark-mode": {
    component: lazy(() => import("@/content/docs/dark-mode.mdx")),
    data: {
  "title": "Dark Mode",
  "description": "Adding dark mode to your site."
},
    headings: [
  {
    "depth": 3,
    "text": "Wrap your root layout",
    "slug": "wrap-your-root-layout"
  },
  {
    "depth": 3,
    "text": "Add a mode toggle",
    "slug": "add-a-mode-toggle"
  }
]
  },
  "installation": {
    component: lazy(() => import("@/content/docs/installation.mdx")),
    data: {
  "title": "Installation",
  "description": "How to install dependencies and get required component for your app."
},
    headings: [
  {
    "depth": 3,
    "text": "Install dependencies",
    "slug": "install-dependencies"
  },
  {
    "depth": 3,
    "text": "Add component",
    "slug": "add-component"
  }
]
  },
  "introduction": {
    component: lazy(() => import("@/content/docs/introduction.mdx")),
    data: {
  "title": "Introduction",
  "description": "Re-usable components built using Kobalte UI and your choice of CSS frameworks."
},
    headings: [
  {
    "depth": 2,
    "text": "Open Code",
    "slug": "open-code"
  },
  {
    "depth": 2,
    "text": "Composition",
    "slug": "composition"
  },
  {
    "depth": 2,
    "text": "Distribution",
    "slug": "distribution"
  },
  {
    "depth": 2,
    "text": "Beautiful Defaults",
    "slug": "beautiful-defaults"
  }
]
  },
  "theming": {
    component: lazy(() => import("@/content/docs/theming.mdx")),
    data: {
  "title": "Theming",
  "description": "Using CSS Variables and color utilities for theming."
},
    headings: [
  {
    "depth": 2,
    "text": "CSS Variables",
    "slug": "css-variables"
  },
  {
    "depth": 2,
    "text": "Utility classes",
    "slug": "utility-classes"
  },
  {
    "depth": 2,
    "text": "Convention",
    "slug": "convention"
  },
  {
    "depth": 2,
    "text": "List of variables",
    "slug": "list-of-variables"
  },
  {
    "depth": 2,
    "text": "Adding new colors",
    "slug": "adding-new-colors"
  },
  {
    "depth": 2,
    "text": "Other color formats",
    "slug": "other-color-formats"
  }
]
  },
};