// @ts-nocheck
// Auto-generated by scripts/index.ts
// Do not edit this file directly.
    
export const Index: Record<string, any> = {
  "unocss": {
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/accordion.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "alert": {
      name: "alert",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/alert.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
      {
            "path": "ui/alert-dialog.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/badge.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "breadcrumbs": {
      name: "breadcrumbs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/breadcrumbs.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "button-group": {
      name: "button-group",
      description: "",
      type: "registry:ui",
      registryDependencies: ["separator"],
      files: [
      {
            "path": "ui/button-group.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/button.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "calendar": {
      name: "calendar",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
      {
            "path": "ui/calendar.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/card.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "carousel": {
      name: "carousel",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
      {
            "path": "ui/carousel.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "chart": {
      name: "chart",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/chart.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/checkbox.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "collapsible": {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/collapsible.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "combobox": {
      name: "combobox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/combobox.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "command": {
      name: "command",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/command.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "context-menu": {
      name: "context-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/context.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "drawer": {
      name: "drawer",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/drawer.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/dropdown-menu.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "file-field": {
      name: "file-field",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/file-field.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "hover-card": {
      name: "hover-card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/hover-card.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "kbd": {
      name: "kbd",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/kbd.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "menubar": {
      name: "menubar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/menubar.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "navigation-menu": {
      name: "navigation-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/navigation-menu.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "number-field": {
      name: "number-field",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/number-field.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "otp-field": {
      name: "otp-field",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/otp-field.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "pagination": {
      name: "pagination",
      description: "",
      type: "registry:ui",
      registryDependencies: ["button"],
      files: [
      {
            "path": "ui/pagination.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "popover": {
      name: "popover",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/popover.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "progress": {
      name: "progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/progress.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "radio-group": {
      name: "radio-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/radio-group.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "resizable": {
      name: "resizable",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/resizable.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "search": {
      name: "search",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/search.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "segmented-control": {
      name: "segmented-control",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/segmented-control.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/select.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "separator": {
      name: "separator",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/separator.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "sidebar": {
      name: "sidebar",
      description: "",
      type: "registry:ui",
      registryDependencies: ["use-mobile","call-handler","button","drawer","separator","skeleton","tooltip"],
      files: [
      {
            "path": "ui/sidebar.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "skeleton": {
      name: "skeleton",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/skeleton.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "slider": {
      name: "slider",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/slider.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "sonner": {
      name: "sonner",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/sonner.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "switch": {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/switch.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "table": {
      name: "table",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/table.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/tabs.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "text-field": {
      name: "text-field",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/text-field.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "toggle-group": {
      name: "toggle-group",
      description: "",
      type: "registry:ui",
      registryDependencies: ["toggle-button"],
      files: [
      {
            "path": "ui/toggle-group.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "toggle-button": {
      name: "toggle-button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/toggle-button.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
    "tooltip": {
      name: "tooltip",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
      {
            "path": "ui/tooltip.tsx",
            "type": "registry:ui",
            "target": ""
      }
]
    },
  }
}
